---
# reference: https://cirrus-ci.org/guide/writing-tasks/

container:
  cpu: 1
  memory: "2G"

# Sanity checks
lint_markdown_task:
  name: "Lint Markdown"
  container:
    image: "docker.io/library/node:latest"
  install_script: "npm install -g markdownlint-cli"
  lint_script: "markdownlint *.md docs/*.md"

lint_yaml_task:
  name: "Lint YAML"
  container:
    image: "docker.io/library/alpine:latest"
  install_script: "apk update && apk add yamllint"
  lint_script: "yamllint ."

lint_containerfile_task:
  name: "Lint Containerfile"
  container:
    image: "docker.io/hadolint/hadolint:latest-alpine"
  lint_script: "hadolint container/Containerfile"

# Build
env:
  # yamllint disable-line rule:line-length
  DOCKER_USERNAME: "ENCRYPTED[!f1238a40d68755898657f4c8e7dec33b437663f11856728ba961174636ae1c3ebf83cd07264480614e59a3a19dadb265!]"
  # yamllint disable-line rule:line-length
  DOCKER_PASSWORD: "ENCRYPTED[!04e259668463baaf0512bf7e1fc3b6ea1880ace531578fcb28a74396924f4e2cdc74340b9671549bb47d1761a723f976!]"

## PRs, Branches
branch_docker_builder:
  name: "Build branch image"
  only_if: "$CIRRUS_CI == 'true' &&
            $CIRRUS_BRANCH != $CIRRUS_DEFAULT_BRANCH &&
            $CIRRUS_REPO_OWNER == 'whiletruedoio'"
  depends_on:
    - "Lint Markdown"
    - "Lint YAML"
    - "Lint Containerfile"
  build_script: "docker image build
                --tag docker.io/whiletruedoio/template:$CIRRUS_BUILD_ID
                --file container/Containerfile
                container/"

## Devel images
devel_docker_builder:
  name: "Build and push devel image"
  only_if: "$CIRRUS_CI == 'true' &&
            $CIRRUS_BRANCH == $CIRRUS_DEFAULT_BRANCH &&
            $CIRRUS_REPO_OWNER == 'whiletruedoio' &&
            $CIRRUS_TAG == ''"
  depends_on:
    - "Lint Markdown"
    - "Lint YAML"
    - "Lint Containerfile"
  build_script: "docker image build
                --tag docker.io/whiletruedoio/template:devel
                --file container/Containerfile
                container/"
  login_script: "docker login
                --username $DOCKER_USERNAME
                --password $DOCKER_PASSWORD"
  push_script: "docker image push
                --all-tags docker.io/whiletruedoio/template"

## Stable images
stable_docker_builder:
  name: "Build and push stable image"
  only_if: "$CIRRUS_CI == 'true' &&
            $CIRRUS_BRANCH == $CIRRUS_DEFAULT_BRANCH &&
            $CIRRUS_REPO_OWNER == 'whiletruedoio' &&
            $CIRRUS_TAG != ''"
  depends_on:
    - "Lint Markdown"
    - "Lint YAML"
    - "Lint Containerfile"
  build_script: "docker image build
                --tag docker.io/whiletruedoio/template:$CIRRUS_TAG
                --tag docker.io/whiletruedoio/template:latest
                --file container/Containerfile
                container/"
  login_script: "docker login
                --username $DOCKER_USERNAME
                --password $DOCKER_PASSWORD"
  push_script: "docker image push
                --all-tags docker.io/whiletruedoio/template"
...
